#!/bin/bash
##########################################################################
# Copyright (c) 2014 - 2017, 2018 Timothy Savannah All Rights Reserved
#
#  Licensed under terms of the LGPLv2
#
#########################################


# isfloat - Check if a given argument is an integer
#   or a float (has a decimal)

if [[ $# -eq 0 ]];
then
    echo "Usage: isfloat [potential float]" >&2
    exit 1;
fi


if [[ $# -gt 1 ]];
then
    exit 1;
fi

if [[ -z "$1" ]];
then
    exit 1;
fi

if ( echo "$1" | grep -qE '^[0-9]*([\.][0-9][0-9]*){0,1}$' );
then
    exit 0;
else
    exit 1;
fi

