#!/usr/bin/env python3
# vim: set ts=4 sw=4 st=4 expandtab:

import os
import sys

def printUsage():
    sys.stderr.write('Usage: prefixitems (-f) (-l) [prefix] [items...]\n  Prefix all items with then given prefix.\nOptions:\n If -f is provided, items will be one or more filenames.\n If -l is provided, items will be printed one per line.\n')

if __name__ == '__main__':
    if len(sys.argv) == 1 or '--help' in sys.argv:
        printUsage()
        sys.exit(1)

    args = sys.argv[1:]

    if '-f' in args:
        args.remove('-f')
        isFiles = True
    else:
        isFiles = False

    if '-l' in args:
        args.remove('-l')
        joinChar = '\n'
    else:
        joinChar = ' '

    if len(args) < 2:
        sys.stderr.write('Not enough arguments.\n')
        printUsage()
        sys.exit(1)

    prefix = args[0]

    if isFiles is True:
        items = []
        for fname in args[1:]:
            if not os.path.isfile(fname):
                sys.stderr.write('File "%s" does not exist or is not a file.\n' %(fname,))
                sys.exit(2)
            with open(fname, 'rt') as f:
                contents = f.read()
            lines = contents.split('\n')
            if lines[-1] == '':
                lines = lines[:-1]
            items += lines
    else:
        items = args[1:]


    sys.stdout.write(joinChar.join([prefix + item for item in items]))
    sys.stdout.write('\n')


# vim: set ts=4 sw=4 st=4 expandtab:
