#!/bin/bash
##########################################################################
# Copyright (c) 2014 - 2017, 2018 Timothy Savannah All Rights Reserved
#
#  Licensed under terms of the LGPLv2
#
#########################################


MSG="$1"
shift
if [ $# -eq 0 ];
then
	printf "$MSG" >&2
	read x
	printf "$x"
else
	unset x
	printf "$MSG" >&2
	read x
	while echo "$x" | notin "$@";
	do
		printf "$MSG" >&2
		read x
	done
	printf "$x"
fi 
