#!/usr/bin/env python

# 

import sys

def printUsage():
    sys.stderr.write('Usage: readall (options)\n  Reads from stdin and outputs on stdout.\n\nUse for input capture in shell scripts\n\n  Options:\n\n    -e\t\tEscape newline,tab,CR instead of doing literals. Like for use with echo -e\n\nExample: X=$(readall)\n')

if __name__ == '__main__':
    if '--help' in sys.argv:
        printUsage()
        sys.exit(0)
    if len(sys.argv) > 2:
        printUsage()
        sys.exit(1)

    doEscape = False
    if len(sys.argv) == 2:
        if sys.argv[1] == '-e':
            doEscape = True
        else:
            sys.stderr.write('Invalid argument: %s\n\n' %(sys.argv[1],))
            printUsage()
            sys.exit(1)
            

    contents = sys.stdin.read()
    if doEscape:
        contents = contents.replace('\\', '\\\\').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
    sys.stdout.write(contents)
