#!/bin/bash
##########################################################################
# Copyright (c) 2014 - 2017, 2018 Timothy Savannah All Rights Reserved
#
#  Licensed under terms of the LGPLv2
#
#########################################


if [ $# -eq 0 ];
then
    STR="$(readall)"
else
    STR="$@"
fi

echo "${STR}" | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g'
