#!/bin/bash
##########################################################################
# Copyright (c) 2014 - 2017, 2018 Timothy Savannah All Rights Reserved
#
#  Licensed under terms of the LGPLv2
#
#########################################

#  Performs a compariso expression and echos "true" / returns 0, or echos "false" and returns nonzero

if [ $@ ];
then
    echo "true"
    exit 0
else
    RET=$?
    echo "false"
    exit ${RET}
fi
