#!/bin/bash
##########################################################################
# Copyright (c) 2014 - 2017, 2018 Timothy Savannah All Rights Reserved
#
#  Licensed under terms of the LGPLv2
#
#########################################

#  teq - "te QUIET" - Performs a given test and returns 0 if true or non-zero otherwise.

if [ $@ ];
then
    exit 0
else
    RET=$?
    exit ${RET}
fi
